#Script for getting Serrated and Tubular adenoma gene expression signatures for GSEA analyses.

# Main steps:
#1) Get the Tubular vs. Serrated diff. expression analyses generated by GEO2R.
#2) Get the top 100, 250, 500 and 1000 up and down genes as signatures for Tubular and Serrated adenoma. In the De Sousa E Melo paper (Nat. Med., PMID 23584090), they have used up to the top 1000 Tubular and Serrated genes for GSEA (Fig. S7). 
#3) Create gmt file.


rm(list=ls())
library(data.table)

#Load Tubular vs. Serrated diff. expression analyses generated by GEO2R.
GSE45270.Tubular_Vs_Serrated_DiffExpr <- fread("D:/HariEaswaran/R_Working_Directory_onc-cbio/Required_Files/GSEA/Serrated_TubularAdenoma_Signature/GEO2R_Data/GSE45270.Tubular_Vs_Serrated_DiffExpr.tsv")

########################
# Get Top 100, 250, 500 and 1000 geneIDs Tubular Adenoma signature
########################
Tubular_up <- GSE45270.Tubular_Vs_Serrated_DiffExpr[GSE45270.Tubular_Vs_Serrated_DiffExpr$logFC > 0 & GSE45270.Tubular_Vs_Serrated_DiffExpr$adj.P.Val <= 0.01]
Tubular_up <- Tubular_up[order(Tubular_up$logFC, decreasing = T)]
which(Tubular_up$Gene.ID %in% "")
Tubular_up <- Tubular_up[-which(Tubular_up$Gene.ID %in% "")]
length(unique(Tubular_up$Gene.ID))

Tubular_up <- Tubular_up[!duplicated(Tubular_up$Gene.ID)]

#Top 100
Tubular_up.geneID_top100 <- Tubular_up$Gene.ID[1:100]
Tubular_up.geneID_top100 <- sapply(Tubular_up.geneID_top100, FUN=function(i){
  strsplit(i, split="///")[[1]]
}) # Some affy probes are associated with 2 or more geneIDs. Just retain all these assocaited IDs.
Tubular_up.geneID_top100 <- unique(unname(unlist(Tubular_up.geneID_top100)))
length(Tubular_up.geneID_top100)

#Top 250
Tubular_up.geneID_top250 <- Tubular_up$Gene.ID[1:250]
Tubular_up.geneID_top250 <- sapply(Tubular_up.geneID_top250, FUN=function(i){
  strsplit(i, split="///")[[1]]
}) # Some affy probes are associated with 2 or more geneIDs. Just retain all these assocaited IDs.
Tubular_up.geneID_top250 <- unique(unname(unlist(Tubular_up.geneID_top250)))
length(Tubular_up.geneID_top250)

#Top 500
Tubular_up.geneID_top500 <- Tubular_up$Gene.ID[1:500]
Tubular_up.geneID_top500 <- sapply(Tubular_up.geneID_top500, FUN=function(i){
  strsplit(i, split="///")[[1]]
}) # Some affy probes are associated with 2 or more geneIDs. Just retain all these assocaited IDs.
Tubular_up.geneID_top500 <- unique(unname(unlist(Tubular_up.geneID_top500)))
length(Tubular_up.geneID_top500)

#Top 1000
Tubular_up.geneID_top1000 <- Tubular_up$Gene.ID[1:1000]
Tubular_up.geneID_top1000 <- sapply(Tubular_up.geneID_top1000, FUN=function(i){
  strsplit(i, split="///")[[1]]
}) # Some affy probes are associated with 2 or more geneIDs. Just retain all these assocaited IDs.
Tubular_up.geneID_top1000 <- unique(unname(unlist(Tubular_up.geneID_top1000)))
length(Tubular_up.geneID_top1000)

########################
# Get Top 100, 250, 500 and 1000 geneIDs for Serrated Adenoma signature
########################
Serrated_up <- GSE45270.Tubular_Vs_Serrated_DiffExpr[GSE45270.Tubular_Vs_Serrated_DiffExpr$logFC < 0 & GSE45270.Tubular_Vs_Serrated_DiffExpr$adj.P.Val <= 0.01]
Serrated_up <- Serrated_up[order(Serrated_up$logFC, decreasing = T)]
which(Serrated_up$Gene.ID %in% "")
Serrated_up <- Serrated_up[-which(Serrated_up$Gene.ID %in% "")]
length(unique(Serrated_up$Gene.ID))

Serrated_up <- Serrated_up[!duplicated(Serrated_up$Gene.ID)]

#Top 100
Serrated_up.geneID_top100 <- Serrated_up$Gene.ID[1:100]
Serrated_up.geneID_top100 <- sapply(Serrated_up.geneID_top100, FUN=function(i){
  strsplit(i, split="///")[[1]]
}) # Some affy probes are associated with 2 or more geneIDs. Just retain all these assocaited IDs.
Serrated_up.geneID_top100 <- unique(unname(unlist(Serrated_up.geneID_top100)))
length(Serrated_up.geneID_top100)

#Top 250
Serrated_up.geneID_top250 <- Serrated_up$Gene.ID[1:250]
Serrated_up.geneID_top250 <- sapply(Serrated_up.geneID_top250, FUN=function(i){
  strsplit(i, split="///")[[1]]
}) # Some affy probes are associated with 2 or more geneIDs. Just retain all these assocaited IDs.
Serrated_up.geneID_top250 <- unique(unname(unlist(Serrated_up.geneID_top250)))
length(Serrated_up.geneID_top250)

#Top 500
Serrated_up.geneID_top500 <- Serrated_up$Gene.ID[1:500]
Serrated_up.geneID_top500 <- sapply(Serrated_up.geneID_top500, FUN=function(i){
  strsplit(i, split="///")[[1]]
}) # Some affy probes are associated with 2 or more geneIDs. Just retain all these assocaited IDs.
Serrated_up.geneID_top500 <- unique(unname(unlist(Serrated_up.geneID_top500)))
length(Serrated_up.geneID_top500)

#Top 1000
Serrated_up.geneID_top1000 <- Serrated_up$Gene.ID[1:1000]
Serrated_up.geneID_top1000 <- sapply(Serrated_up.geneID_top1000, FUN=function(i){
  strsplit(i, split="///")[[1]]
}) # Some affy probes are associated with 2 or more geneIDs. Just retain all these assocaited IDs.
Serrated_up.geneID_top1000 <- unique(unname(unlist(Serrated_up.geneID_top1000)))
length(Serrated_up.geneID_top1000)

########################
# Create gmt file
########################
# Convert the list to a GeneSetCollection using GSEABase functionality
library(GSEABase)

adenomaTubularSerratedGeneSetList <- list(
  top100_TubularAdenomaSignature=Tubular_up.geneID_top100,
  top250_TubularAdenomaSignature=Tubular_up.geneID_top250,
  top500_TubularAdenomaSignature=Tubular_up.geneID_top500,
  top1000_TubularAdenomaSignature=Tubular_up.geneID_top1000,
  top100SerratedAdenomaSignature=Serrated_up.geneID_top100,
  top250SerratedAdenomaSignature=Serrated_up.geneID_top250,
  top500SerratedAdenomaSignature=Serrated_up.geneID_top500,
  top1000SerratedAdenomaSignature=Serrated_up.geneID_top1000
  )

sapply(adenomaTubularSerratedGeneSetList, length)

myGeneSetList <- list()
for (i in 1:length(adenomaTubularSerratedGeneSetList)) {
  myGeneSetList[[i]] <- GeneSet(adenomaTubularSerratedGeneSetList[[i]], setName = names(adenomaTubularSerratedGeneSetList)[i])
}

#Convert the list to a GeneSetCollection using GSEABase functionality
adenomaTubularSerratedGeneSetList <- GeneSetCollection(myGeneSetList)

# Convert GeneSetCollection to gmt format
toGmt(adenomaTubularSerratedGeneSetList, con = "D:/HariEaswaran/R_Working_Directory_onc-cbio/Required_Files/GSEA/Serrated_TubularAdenoma_Signature/Serrated_TubularAdenoma_Signature/adenomaTubularSerratedGeneSet.gmt")
